gamma: 0.99
lr: 0.0001
batch_size: 64
number_episodes: 2000
replay_memory_size: 50000
optimize_every_n_steps: 4
epsilon_decay: 0.9995
save_every_n_episodes: 50
continue_from_checkpoint_path: null
target_update: 500
