gamma: 0.9
lr: 0.001
batch_size: 256
number_episodes: 100000000
replay_memory_size: 100000
optimize_every_n_steps: 512
epsilon_decay: 0.9995
save_every_n_episodes: 5000
continue_from_checkpoint_path: null # /home/rayanramoul/Documents/Github/rl-chess/checkpoints/last.ckpt
